#!/bin/bash
# Build the on-prem bundles and the capnp module lists that name them.
#
# The bundling is done by wrangler, deliberately: it is the exact bundler that produces the
# hosted artifact, so on-prem and hosted come out of one pipeline and cannot drift in the way
# a second hand-rolled build would. Nothing here deploys, and wrangler.build.jsonc carries no
# ids, routes or secrets.
#
# The generated step exists because wrangler emits each migration as a separate text module
# under a content-hashed name, and workerd's config cannot glob: every module has to be named.
# Hashes change whenever a migration changes, so the list is generated rather than maintained.
set -euo pipefail

cd "$(dirname "$0")"
ROOT="$(pwd)"

build() {
  local worker="$1"
  # files/ arrives in its own change, once the R2 shim and the blob sidecar exist. Skipping is
  # louder than a missing line here would be: the message says what is not built yet.
  if [ ! -f "$worker/wrangler.build.jsonc" ]; then
    echo "==> skipping $worker (no $worker/wrangler.build.jsonc yet)"
    return 0
  fi
  echo "==> building $worker"

  # The Apple library is a real dependency of the App Store activation path and is imported
  # inside the handler, so it has to be installed before bundling.
  ( cd "$worker-worker" && npm install --silent --no-audit --no-fund )

  ( cd "$worker" && npx --yes wrangler@latest deploy --dry-run \
      --outdir="$ROOT/dist/$worker" -c wrangler.build.jsonc >/dev/null )

  # Module list: the entry, then every emitted .sql as a text module. Names must match how the
  # bundle imports them, which is the bare filename.
  local out="dist/$worker/modules.capnp"
  {
    echo "# GENERATED by selfhost/build.sh. Do not edit."
    echo "using Workerd = import \"/workerd/workerd.capnp\";"
    echo "const modules :List(Workerd.Worker.Module) = ["
    echo "  (name = \"entry.js\", esModule = embed \"entry.js\"),"
    for f in "dist/$worker"/*.sql; do
      [ -e "$f" ] || continue
      echo "  (name = \"$(basename "$f")\", text = embed \"$(basename "$f")\"),"
    done
    echo "];"
  } > "$out"

  echo "    $(ls -1 "dist/$worker"/*.sql 2>/dev/null | wc -l | tr -d ' ') migrations, $(du -h "dist/$worker/entry.js" | cut -f1) bundle"
}

build messaging
build files

echo "==> done"
